title: Ikhsan Salsabily
email: 
description: My name is Ikhsan Salsabily, and I am a second-semester student. 
             I was born in Lhokseumawe on May 1, 2006. I am currently studying at the State Polytechnic of Lhokseumawe,
             majoring in Informatics Engineering.


url: "https://isanbily06.github.io"


plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag

 